name: publish

on:
  release:
    types: [ created ]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment:
      name: pypi
      url: https://pypi.org/p/tinypypi
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install build tools
      run: |
        python -m pip install -U pip
        python -m pip install build
    - name: Build package
      run: |
        python -m build --outdir dist/ .
    - name: Install package
      run: python -m pip install dist/*.whl
    - name: Run unit-tests
      run: |
        python -m pip install pytest
        python -m pytest -vvra
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
